---
apiVersion: v1
kind: Pod
metadata: 
  name: hw141envsecret
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: key
      valueFrom:
        secretKeyRef:
          name: domain-cert
          key: tls.key
    - name: cert
      valueFrom:
        secretKeyRef:
          name: domain-cert
          key: tls.crt
