apiVersion: v1
kind: Pod
metadata: 
  name: hw141volumesecret
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: secret-volume
      mountPath: "/opt/secretvolume"
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: domain-cert
