---
- name: hw121
  hosts: 127.0.0.1
  connection: local
  become: true
  tasks:
    - name: Create a k8s namespace
      k8s:
        name: hello-namespace
        api_version: v1
        kind: Namespace
        state: present

    - name: Deployment
      k8s:
        api_version: v1
        namespace: hello-namespace
        definition:
          kind: Deployment
          metadata:
            labels:
              app: helloworld
            name: helloworld
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: helloworld
            template:
              metadata:
                labels:
                  app: helloworld
              spec:
                containers:
                  - name: helloworld
                    image: k8s.gcr.io/echoserver:1.4
                    ports:
                    - containerPort: 8080
                      protocol: TCP
    - name: Create service
      k8s:
        api_version: v1
        definition:
          kind: Service
          metadata:
            name: helloworld
            namespace: hello-namespace
            labels:
              app: helloworld
          spec:
            type: NodePort
            selector:
              app: helloworld
            ports:
            - port: 8080
              targetPort: 8080
              nodePort: 30080