apiVersion: apps/v1
kind: Deployment
metadata:
  name: fbdpl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fb
  template:
    metadata:
      labels:
        app: fb
    spec:
      containers:
      - name: front
        image: imustgetout/hw131frontend:v1.1
        ports:
        - containerPort: 80
        volumeMounts:
        - name: static
          mountPath: /static
      - name: back
        image: imustgetout/hw131backend:v1.1
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: static
          mountPath: /static
      volumes:
      - name: static
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: fb-svc
spec:
  type: NodePort
  selector:
    app: fb
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 80
    nodePort: 30080

