apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "back.fullname" . }}
  labels:
    {{- include "back.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "back.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "back.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - protocol: TCP
              containerPort: 9000
          env: 
          - name: DATABASE_URL
            value: postgres://postgres:postgres@db:5432/news