---
- name: Install Redis
  hosts: all
  roles: 
    - { role: rvm.ruby,
        tags: ruby,
        rvm1_rubies: ['ruby-3.0.3'],
        rvm1_user: andrey
      }
    - { role: redis,
        tags: redis
      }