apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-dpl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-pod
  template:
    metadata:
      labels:
        app: front-pod
    spec:
      containers:
      - name: front
        image: imustgetout/hw131frontend:v1.1
        ports:
        - containerPort: 80
        volumeMounts:
        - name: sharevol
          mountPath: /static
        env:
        - name: BASE_URL
          value: http://hw131-back-svc:9000
      volumes:
      - name: sharevol
        persistentVolumeClaim:
          claimName: sharevol
---
apiVersion: v1
kind: Service
metadata:
  name: front-svc
spec:
  type: NodePort
  selector:
    app: front-pod
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 80
    nodePort: 30080
